// 🌊 this file is auto-generated by 404 Software's script. don't edit it.
// https://404-software.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

const Paragraph = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" {...props}><Path d="M448 63.1C448 81.67 433.7 96 416 96H384v352c0 17.67-14.33 32-31.1 32S320 465.7 320 448V96h-32v352c0 17.67-14.33 32-31.1 32S224 465.7 224 448v-96H198.9c-83.57 0-158.2-61.11-166.1-144.3C23.66 112.3 98.44 32 191.1 32h224C433.7 32 448 46.33 448 63.1z" /></Svg>;

export default Paragraph;