// 🌊 this file is auto-generated by 404 Software's script. don't edit it.
// https://404-software.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const BandcampBrands = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="currentColor" {...props}><Path d="M256,8C119,8,8,119,8,256S119,504,256,504,504,393,504,256,393,8,256,8Zm48.2,326.1h-181L207.9,178h181Z" /></Svg>;
export default BandcampBrands;