// 🌊 this file is auto-generated by 404 Software's script. don't edit it.
// https://404-software.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const SquareFullSolid = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="currentColor" {...props}><Path d="M0 0H512V512H0V0z" /></Svg>;
export default SquareFullSolid;